// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eideyzrojfkkqyajlbyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpZGV5enJvamZra3F5YWpsYnl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDYyODYsImV4cCI6MjA2Nzk4MjI4Nn0.phQon5oU5y7LUWPNqNQT020iJV1FtNlqtGLDs94fi0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});