server:
  port: 8080

spring:
  application:
    name: account-service
  profiles:
    active: local
  
  datasource:
    url: jdbc:postgresql://localhost:5432/xpend_dev
    username: xpend_user
    password: xpend_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
    
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: xpend_user
    password: xpend_pass
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms

logging:
  level:
    com.xpend.account: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  file:
    name: logs/account-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:ZGVmYXVsdC1zZWNyZXQta2V5LWZvci1kZXZlbG9wbWVudC1vbmx5LWNoYW5nZS1pbi1wcm9kdWN0aW9u}
  expiration: 900000 # 15 minutes
  refresh-expiration: 604800000 # 7 days

# API Rate Limiting
api:
  rate-limit:
    enabled: true
    requests-per-minute: 100
    burst-capacity: 20

# Encryption Configuration
encryption:
  key: ${ENCRYPTION_KEY:bXktc2VjcmV0LWVuY3J5cHRpb24ta2V5LWZvci1kZXZlbG9wbWVudA==}
  algorithm: AES/GCB/PKCS5Padding

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/xpend_dev
  data:
    redis:
      host: redis
  rabbitmq:
    host: rabbitmq

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false