server:
  port: 8080

spring:
  application:
    name: category-service
  profiles:
    active: local
  
  datasource:
    url: jdbc:postgresql://localhost:5432/xpend_dev
    username: xpend_user
    password: xpend_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: xpend_user
    password: xpend_pass

logging:
  level:
    com.xpend.category: DEBUG
  file:
    name: logs/category-service.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:ZGVmYXVsdC1zZWNyZXQta2V5LWZvci1kZXZlbG9wbWVudC1vbmx5LWNoYW5nZS1pbi1wcm9kdWN0aW9u}
  expiration: 900000

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/xpend_dev
  data:
    redis:
      host: redis
  rabbitmq:
    host: rabbitmq